package io.pfaumc.pfauprotect.command

import io.pfaumc.pfauprotect.Ui
import io.pfaumc.pfauprotect.model.Cause
import io.pfaumc.pfauprotect.model.Cause.*
import io.pfaumc.pfauprotect.tr
import net.kyori.adventure.text.Component

/**
 * What a cause reads as on a lookup line. The Russian is a noun of the action rather than a verb: a past
 * verb has a gender, and the ledger does not know the reader's. Where the cause is a thing of the game — a
 * creeper, a hopper — the line names it through the game's own translation.
 */
internal fun verb(cause: Cause): Component = when (cause) {
    PICKUP -> w("picked up", "подбор")
    DROP_FROM_HAND, DROP_FROM_MENU, DROP_MENU_CLOSE -> w("dropped", "выброс")
    DROP_ON_DISCONNECT -> w("dropped on quit", "выброс при выходе")
    INVENTORY_OVERFLOW_DROP -> w("dropped, no room", "выпало, нет места")
    CURSOR_PLACE, CURSOR_TAKE, CURSOR_SWAP, QUICK_MOVE, HOTBAR_SWAP, OFFHAND_SWAP, COLLECT_ALL,
    QUICK_CRAFT_DISTRIBUTE -> w("moved", "перекладка")
    EQUIP_ARMOR -> w("put on", "надевание")
    UNEQUIP_ARMOR -> w("took off", "снятие")
    MENU_CLOSE_RETURN -> w("returned on close", "возврат при закрытии")
    DEATH_DROP -> w("dropped on death", "выпало при смерти")
    DEATH_DESTROY_VANISHING -> w("vanished on death", "исчезло при смерти")
    TOTEM_CONSUME -> i("totem_of_undying")
    INVENTORY_LOAD -> w("loaded", "загрузка")
    ITEM_VANISHED, ITEM_DESPAWN -> w("vanished", "исчезновение")
    ROLLBACK -> w("rollback", "откат")
    ENTITY_KILLED -> w("killed", "убийство")
    ENTITY_BROKEN -> w("broke", "поломка")
    MOB_BRED -> w("bred", "разведение")
    ENTITY_CHANGED -> w("changed", "изменение")
    ENTITY_LED -> w("led away", "увод")
    PLAYER_KILLED -> w("killed a player", "убийство игрока")
    BLK_LIQUID_FLOW -> w("flowed", "растекание")
    PURGE_OPENING -> w("opening balance", "начальный остаток")
    BLK_PLUGIN -> w("plugin", "плагин")
    CONTAINER_ADD -> w("put in", "вложение")
    CONTAINER_REMOVE -> w("took out", "изъятие")
    CONTAINER_BREAK_DROP -> w("spilled on break", "выпало при поломке")
    CONTAINER_BREAK_PACK -> w("packed on break", "упаковано при поломке")
    CONTAINER_PLACE_UNPACK -> w("unpacked on place", "распаковано при установке")
    HOPPER_PULL_CONTAINER, HOPPER_PULL_GROUND, HOPPER_PUSH -> b("hopper")
    HOPPER_MINECART_PULL -> e("hopper_minecart")
    DROPPER_PUSH, DROPPER_EJECT -> b("dropper")
    DISPENSER_EJECT, DISPENSER_BEHAVIOR, BLK_DISPENSER, DISPENSED_PROJECTILE -> b("dispenser")
    CRAFTER_CONSUME, CRAFTER_EMIT -> b("crafter")
    FURNACE_FUEL_CONSUME, FURNACE_FUEL_REMAINDER, SMELT -> b("furnace")
    BREWING_INGREDIENT_CONSUME, BREWING_FUEL_CONSUME, BREW -> b("brewing_stand")
    COMPOSTER_CONSUME, COMPOSTER_BONEMEAL -> b("composter")
    CAMPFIRE_COOK_DROP -> b("campfire")
    BEEHIVE_HARVEST -> b("beehive")
    BRUSHABLE_REVEAL -> i("brush")
    CONTAINER_NAMED, NAME_TAG -> w("named", "имя")
    ITEM_SPAWN -> w("appeared", "появление")
    ITEM_MERGE -> w("merged", "слияние")
    ITEM_PICKUP_BY_MOB, ITEM_PICKUP_BY_MOB_INV -> w("picked up by a mob", "подбор мобом")
    ITEM_DESTROY_FIRE, BLK_FIRE_BURN -> w("burnt", "сгорание")
    ITEM_DESTROY_CACTUS -> b("cactus")
    ITEM_DESTROY_VOID -> w("fell into the void", "падение в пустоту")
    ITEM_DESTROY_EXPLOSION, BLK_EXPLOSION -> w("explosion", "взрыв")
    MOB_THROW_ITEM -> w("thrown by a mob", "бросок мобом")
    BLOCK_DROP -> w("fell out of a block", "выпало из блока")
    MOB_DROP -> w("mob drop", "выпало из моба")
    MOB_EQUIPMENT_DROP, MOB_SPAWN_EQUIPMENT, MOB_EQUIPMENT_LOST, EQUIP_MOB -> w("mob gear", "снаряжение моба")
    LOOT_GENERATE -> w("loot", "добыча")
    VAULT_REWARD -> b("vault")
    TRIAL_SPAWNER_REWARD -> b("trial_spawner")
    FISHING_CATCH -> i("fishing_rod")
    TRADE_RESULT, TRADE_PAYMENT -> w("trade", "торговля")
    PIGLIN_BARTER -> e("piglin")
    GIFT_DROP -> w("gift", "подарок")
    SHEARING_DROP, SHEAR_MOB -> i("shears")
    BLOCK_INTERACT_DROP -> w("fell out on use", "выпало при использовании")
    ADVANCEMENT_REWARD -> w("advancement", "достижение")
    CREATIVE_SET, CREATIVE_CLONE, CREATIVE_PICK -> w("creative", "творчество")
    DIRECT_NEW_ITEM -> w("new item", "новый предмет")
    BOOK_EDIT -> i("writable_book")
    RECIPE_BOOK_FILL -> w("recipe book", "книга рецептов")
    CRAFT_CONSUME, CRAFT_RESULT, CRAFT_REMAINDER -> b("crafting_table")
    ANVIL_COMBINE -> b("anvil")
    GRINDSTONE -> b("grindstone")
    SMITHING_TRANSFORM, SMITHING_TRIM -> b("smithing_table")
    ENCHANT_APPLY, ENCHANT_LAPIS_CONSUME -> b("enchanting_table")
    STONECUTTER -> b("stonecutter")
    LOOM -> b("loom")
    CARTOGRAPHY, MAP_SCALE_LOCK -> b("cartography_table")
    CONSUME_FOOD -> w("eaten", "еда")
    CONSUME_REMAINDER -> w("leftover", "остаток")
    DURABILITY_DAMAGE -> w("wear", "износ")
    DURABILITY_BREAK -> w("worn out", "сломано износом")
    TRANSMUTE_ON_BREAK -> w("changed on break", "превращение при поломке")
    DYE_ITEM, DYE_MOB -> w("dyed", "окраска")
    BOOK_SIGN -> i("written_book")
    BOOK_COPY -> w("book copied", "копия книги")
    BANNER_DUPLICATE -> w("banner copied", "копия флага")
    MAP_CLONE -> w("map copied", "копия карты")
    MAP_FILL -> i("map")
    BLOCK_PLACE, BLK_PLAYER_PLACE -> w("placed", "установка")
    BONEMEAL_USE, BLK_BONEMEAL -> i("bone_meal")
    BUCKET_FILL, BUCKET_EMPTY, BLK_BUCKET -> i("bucket")
    SPAWN_EGG_USE -> w("spawn egg", "яйцо призыва")
    WAX_APPLY -> i("honeycomb")
    RECORD_INTO_JUKEBOX -> b("jukebox")
    BOOK_ONTO_LECTERN -> b("lectern")
    ITEM_INTO_SINGLE_BLOCK -> w("put into a block", "вложение в блок")
    PLACE_ENTITY_ITEM -> w("put down", "установка")
    EYE_INTO_FRAME, EYE_SURVIVE, EYE_SHATTER -> i("ender_eye")
    ITEM_USED, BLK_PLAYER_USE -> w("used", "использование")
    BOTTLE_FILL, BOTTLE_EMPTY -> i("glass_bottle")
    CAULDRON_WASH -> b("cauldron")
    BEACON_PAYMENT -> b("beacon")
    FEED_MOB -> w("fed", "кормление")
    TAME_MOB -> w("tamed", "приручение")
    LEASH_ATTACH, LEASH_DROP -> i("lead")
    BUCKET_CAPTURE_MOB, BUCKET_RELEASE_MOB -> i("water_bucket")
    GIVE_ITEM_TO_MOB -> w("given to a mob", "передача мобу")
    ARMOR_STAND_SWAP -> e("armor_stand")
    MOB_TRANSFORM -> w("turned", "превращение")
    ENTITY_BREAK_DROP -> w("fell out of an entity", "выпало из сущности")
    PROJ_SHOT, PROJ_SHOT_PHANTOM, THROWN_CONSUMED -> w("shot", "выстрел")
    PROJ_PICKUP -> w("picked up a shot", "подбор снаряда")
    PROJ_DEFLECT_DROP -> w("deflected", "отражение")
    PROJ_HIT_VOID -> w("shot into the void", "выстрел в пустоту")
    PROJ_DESPAWN -> w("shot vanished", "исчезновение снаряда")
    TRIDENT_LOYALTY_RETURN, TRIDENT_DROP -> i("trident")
    FIREWORK_LAUNCH -> i("firework_rocket")
    BUNDLE_INSERT, BUNDLE_EXTRACT, BUNDLE_DUMP, BUNDLE_SPILL_DESTROYED -> i("bundle")
    CROSSBOW_LOAD, CROSSBOW_SHOOT -> i("crossbow")
    BLK_PLAYER_BREAK -> w("broke", "разрушение")
    BLK_TNT -> b("tnt")
    BLK_CREEPER -> e("creeper")
    BLK_BED_EXPLOSION -> b("red_bed")
    BLK_RESPAWN_ANCHOR -> b("respawn_anchor")
    BLK_END_CRYSTAL -> e("end_crystal")
    BLK_FIRE_SPREAD -> b("fire")
    BLK_LIQUID_DESTROY -> w("washed away", "смыто")
    BLK_LIQUID_FORM -> w("set from liquid", "застывание")
    BLK_PISTON_EXTEND, BLK_PISTON_RETRACT -> b("piston")
    BLK_FALL_START -> w("fell", "падение")
    BLK_FALL_LAND -> w("landed", "приземление")
    BLK_GROW -> w("grew", "рост")
    BLK_LEAF_DECAY -> w("leaves decayed", "опадание листвы")
    BLK_FADE -> w("faded", "увядание")
    BLK_FORM -> w("formed", "образование")
    BLK_SCULK -> b("sculk")
    BLK_ENDERMAN -> e("enderman")
    BLK_WITHER -> e("wither")
    BLK_RAVAGER -> e("ravager")
    BLK_SILVERFISH -> e("silverfish")
    BLK_SNOWMAN -> e("snow_golem")
    BLK_FROST_WALKER -> Component.translatable("enchantment.minecraft.frost_walker")
    BLK_MOB_GRIEF -> w("mob", "моб")
    BLK_PORTAL_CREATE -> w("portal lit", "портал зажжён")
    BLK_PORTAL_DESTROY -> w("portal broken", "портал разрушен")
    BLK_PLAYER_SWITCH -> w("pressed", "нажатие")
    BLK_ENTITY_SWITCH -> w("pressed by an entity", "нажатие сущностью")
    BLK_SPONGE -> b("sponge")
    BLK_COMMAND -> w("command", "команда")
    BLK_SIGN_EDIT -> w("sign edited", "правка таблички")
    BLK_SHAPE -> w("joined anew", "примыкание")
    CMD_GIVE -> c("/give")
    CMD_ITEM_REPLACE, CMD_ITEM_MODIFY, CMD_ITEM_COPY -> c("/item")
    CMD_LOOT -> c("/loot")
    CMD_CLONE_CONTAINER, CMD_CLONE_MOVE_VOID -> c("/clone")
    CMD_DATA_MERGE -> c("/data")
    CMD_SETBLOCK_FILL_FILL, CMD_SETBLOCK_FILL_VOID -> c("/fill")
    CMD_SUMMON_ITEMS -> c("/summon")
    CMD_KILL_ITEM -> c("/kill")
    CMD_ENCHANT -> c("/enchant")
    CMD_CLEAR -> c("/clear")
    UNKNOWN -> w("unknown", "неизвестно")
}

private fun w(en: String, ru: String): Component = Component.text(tr(en, ru))

private fun c(command: String): Component = Component.text(command)

private fun b(key: String) = Ui.block("minecraft:$key")

private fun i(key: String) = Ui.item("minecraft:$key")

private fun e(key: String) = Ui.entity("minecraft:$key")
